spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.daniel: DEBUG